### ISSUE TITLE
Add github label feature

### ISSUE THREAD

**Issue by babarot** [babarot/travis-test#2]
test

**Comment by b4b4r07** [comment]
## Plan result


<pre><code> Plan: 1 to add, 0 to change, 0 to destroy.
</pre></code>

<details><summary>Details (Click me)</summary>
<pre><code> Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.terraform_remote_state.teams_platform_development: Refreshing state...
google_project.my_project: Refreshing state...
aws_iam_policy.datadog_aws_integration: Refreshing state...
aws_iam_user.teams_terraform: Refreshing state...
aws_iam_role.datadog_aws_integration: Refreshing state...
google_project_services.my_project: Refreshing state...
google_bigquery_dataset.gateway_access_log: Refreshing state...
aws_iam_role_policy_attachment.datadog_aws_integration: Refreshing state...
google_logging_project_sink.gateway_access_log_bigquery_sink: Refreshing state...
google_project_iam_member.gateway_access_log_bigquery_sink_writer_is_bigquery_data_editor: Refreshing state...
google_dns_managed_zone.tfnotifyapps_com: Refreshing state...
google_dns_record_set.dev_tfnotifyapps_com: Refreshing state...

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  &#43; create

Terraform will perform the following actions:

  &#43; google_compute_global_address.my_another_project
      id:         &lt;computed&gt;
      address:    &lt;computed&gt;
      ip_version: &#34;IPV4&#34;
      name:       &#34;my-another-project&#34;
      project:    &#34;my-project&#34;
      self_link:  &lt;computed&gt;


Plan: 1 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

Note: You didn&#39;t specify an &#34;-out&#34; parameter to save this plan, so Terraform
can&#39;t guarantee that exactly these actions will be performed if
&#34;terraform apply&#34; is subsequently run.

</pre></code></details>

**Comment by babarot** [comment]
## Plan result


<pre><code> Plan: 1 to add, 0 to change, 0 to destroy.
</pre></code>

<details><summary>Details (Click me)</summary>
<pre><code> Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.terraform_remote_state.teams_platform_development: Refreshing state...
google_project.my_project: Refreshing state...
aws_iam_policy.datadog_aws_integration: Refreshing state...
aws_iam_user.teams_terraform: Refreshing state...
aws_iam_role.datadog_aws_integration: Refreshing state...
google_project_services.my_project: Refreshing state...
google_bigquery_dataset.gateway_access_log: Refreshing state...
aws_iam_role_policy_attachment.datadog_aws_integration: Refreshing state...
google_logging_project_sink.gateway_access_log_bigquery_sink: Refreshing state...
google_project_iam_member.gateway_access_log_bigquery_sink_writer_is_bigquery_data_editor: Refreshing state...
google_dns_managed_zone.tfnotifyapps_com: Refreshing state...
google_dns_record_set.dev_tfnotifyapps_com: Refreshing state...

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  &#43; create

Terraform will perform the following actions:

  &#43; google_compute_global_address.my_another_project
      id:         &lt;computed&gt;
      address:    &lt;computed&gt;
      ip_version: &#34;IPV4&#34;
      name:       &#34;my-another-project&#34;
      project:    &#34;my-project&#34;
      self_link:  &lt;computed&gt;


Plan: 1 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

Note: You didn&#39;t specify an &#34;-out&#34; parameter to save this plan, so Terraform
can&#39;t guarantee that exactly these actions will be performed if
&#34;terraform apply&#34; is subsequently run.

</pre></code></details>
